version: 2
updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@octocat"
    assignees:
      - "@octocat"
    commit-message:
      prefix: "composer"
      prefix-development: "composer-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "php"
    ignore:
      # Ignore major version updates for Laravel
      - dependency-name: "laravel/framework"
        update-types: ["version-update:semver-major"]
      # Ignore patch updates for specific packages
      - dependency-name: "phpunit/phpunit"
        update-types: ["version-update:semver-patch"]

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@octocat"
    assignees:
      - "@octocat"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      # Ignore major version updates for Node.js packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@octocat"
    assignees:
      - "@octocat"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"